// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zspfwjmesflujextcvco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcGZ3am1lc2ZsdWpleHRjdmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjcyOTcsImV4cCI6MjA2MjEwMzI5N30.DGGoB0lAtYKlz8vYtmPeMoXIIL1oUnNMVF4Jv5vY7Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});